# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main
      run: |
        python "main.py"
    
    - name: Commit
      run: |
        git config --local user.email "hammuu1112@gmail.com"
        git config --local user.name "Action bot"
        git add member.json
        git commit -m "[Auto] update member list"
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: $
